version: 1
update_configs:
  - package_manager: "java:gradle"
    directory: "/"
    update_schedule: "monthly"
    automerged_updates:
      - match:
          update_type: "all"
  - package_manager: "java:gradle"
    directory: "/router/"
    update_schedule: "monthly"
    automerged_updates:
      - match:
          update_type: "all"
  - package_manager: "java:gradle"
    directory: "/router-protobuf/"
    update_schedule: "monthly"
    automerged_updates:
      - match:
          update_type: "all"
  - package_manager: "java:gradle"
    directory: "/router-openapi-request-validator/"
    update_schedule: "monthly"
    automerged_updates:
      - match:
          update_type: "all"